[versions]
dokka = "1.9.10"
konf = "1.1.2"
kotest = "5.8.0"
kotlin = "1.8.22"

[libraries]
classgraph = "io.github.classgraph:classgraph:4.8.165"
konf-yaml = { module = "com.uchuhimo:konf-yaml", version.ref = "konf" }
kotest-junit5-jvm = { module = "io.kotest:kotest-runner-junit5-jvm", version.ref = "kotest" }
kotest-assertions-core-jvm = { module = "io.kotest:kotest-assertions-core-jvm", version.ref = "kotest" }
javalin = "io.javalin:javalin:5.6.3"

[bundles]
kotlin-testing = [ "kotest-junit5-jvm", "kotest-assertions-core-jvm" ]

[plugins]
dokka = { id = "org.jetbrains.dokka", version.ref = "dokka" }
gitSemVer = "org.danilopianini.git-sensitive-semantic-versioning:3.1.0"
gradlePluginPublish = "com.gradle.plugin-publish:1.2.1"
jacoco-testkit = "pl.droidsonroids.jacoco.testkit:1.0.12"
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-qa = "org.danilopianini.gradle-kotlin-qa:0.29.2"
multiJvmTesting = "org.danilopianini.multi-jvm-test-plugin:0.5.6"
publishOnCentral = "org.danilopianini.publish-on-central:5.0.10"
taskTree = "com.dorongold.task-tree:2.1.1"
